import 'service_model.dart';

final servicesList = [
  // Standard Cleaning
  ServiceModel(
    id: 'bed_standard',
    title: 'Bedroom (Standard)',
    description: 'Standard bedroom cleaning',
    price: 17.25,
    duration: Duration(minutes: 30),
  ),
  ServiceModel(
    id: 'bath_standard',
    title: 'Bathroom (Standard)',
    description: 'Standard bathroom cleaning',
    price: 21.00,
    duration: Duration(minutes: 35),
  ),
  ServiceModel(
    id: 'half_bath_standard',
    title: 'Half Bathroom (Standard)',
    description: 'Standard half bathroom cleaning',
    price: 10.50,
    duration: Duration(minutes: 20),
  ),
  ServiceModel(
    id: 'other_standard',
    title: 'Other Room (Standard)',
    description: 'Standard other room cleaning',
    price: 26.00,
    duration: Duration(minutes: 40),
  ),

  // Deep Cleaning
  ServiceModel(
    id: 'bed_deep',
    title: 'Bedroom (Deep)',
    description: 'Deep bedroom cleaning',
    price: 23.50,
    duration: Duration(minutes: 45),
  ),
  ServiceModel(
    id: 'bath_deep',
    title: 'Bathroom (Deep)',
    description: 'Deep bathroom cleaning',
    price: 38.50,
    duration: Duration(minutes: 60),
  ),
  ServiceModel(
    id: 'half_bath_deep',
    title: 'Half Bathroom (Deep)',
    description: 'Deep half bathroom cleaning',
    price: 17.00,
    duration: Duration(minutes: 30),
  ),
  ServiceModel(
    id: 'other_deep',
    title: 'Other Room (Deep)',
    description: 'Deep other room cleaning',
    price: 38.50,
    duration: Duration(minutes: 60),
  ),

  // Add-Ons
  ServiceModel(
    id: 'fridge',
    title: 'Refrigerator (inside)',
    description: 'Fridge inside cleaning',
    price: 17.00,
    duration: Duration(minutes: 20),
    isAddon: true,
  ),
  ServiceModel(
    id: 'microwave',
    title: 'Microwave (inside)',
    description: 'Microwave inside cleaning',
    price: 4.25,
    duration: Duration(minutes: 5),
    isAddon: true,
  ),
  ServiceModel(
    id: 'oven',
    title: 'Oven (inside)',
    description: 'Oven inside cleaning',
    price: 19.25,
    duration: Duration(minutes: 25),
    isAddon: true,
  ),
  ServiceModel(
    id: 'stovetop',
    title: 'Stovetop (scrub)',
    description: 'Scrub stovetop',
    price: 8.50,
    duration: Duration(minutes: 15),
    isAddon: true,
  ),
  ServiceModel(
    id: 'dishwasher',
    title: 'Dishwasher (inside)',
    description: 'Dishwasher inside cleaning',
    price: 6.50,
    duration: Duration(minutes: 10),
    isAddon: true,
  ),
  ServiceModel(
    id: 'toaster',
    title: 'Toaster (crumbs)',
    description: 'Remove crumbs from toaster',
    price: 2.25,
    duration: Duration(minutes: 5),
    isAddon: true,
  ),
  ServiceModel(
    id: 'coffee_maker',
    title: 'Coffee Maker (descale)',
    description: 'Descale coffee maker',
    price: 2.25,
    duration: Duration(minutes: 5),
    isAddon: true,
  ),
  ServiceModel(
    id: 'blender',
    title: 'Blender (inside)',
    description: 'Blender inside cleaning',
    price: 2.25,
    duration: Duration(minutes: 5),
    isAddon: true,
  ),
  ServiceModel(
    id: 'washer',
    title: 'Washer (inside)',
    description: 'Washer inside cleaning',
    price: 6.50,
    duration: Duration(minutes: 10),
    isAddon: true,
  ),
  ServiceModel(
    id: 'dryer',
    title: 'Dryer (inside)',
    description: 'Dryer inside cleaning',
    price: 6.50,
    duration: Duration(minutes: 10),
    isAddon: true,
  ),
  ServiceModel(
    id: 'air_fryer',
    title: 'Air Fryer (inside)',
    description: 'Air fryer inside cleaning',
    price: 4.25,
    duration: Duration(minutes: 5),
    isAddon: true,
  ),
  ServiceModel(
    id: 'kettle',
    title: 'Electric Kettle (descale)',
    description: 'Descale kettle',
    price: 2.25,
    duration: Duration(minutes: 5),
    isAddon: true,
  ),
  ServiceModel(
    id: 'dishes',
    title: 'Dishes (wash)',
    description: 'Wash dishes',
    price: 8.50,
    duration: Duration(minutes: 15),
    isAddon: true,
  ),
];
